-- ============================================================================
-- 001_account_setup.sql
-- Commodity Trading Sanctions Risk Analytics Platform
-- Account-level configuration, databases, warehouses, RBAC, governance
-- ============================================================================
-- EXECUTION ORDER: Run this script FIRST with ACCOUNTADMIN role.
-- ============================================================================

USE ROLE ACCOUNTADMIN;

-- ============================================================================
-- SECTION 1: ACCOUNT PARAMETERS
-- ============================================================================

ALTER ACCOUNT SET
    PERIODIC_DATA_REKEYING = TRUE,
    CORTEX_ENABLED_CROSS_REGION = 'ANY_REGION',
    NETWORK_POLICY = '';  -- Will be set after policy creation

-- ============================================================================
-- SECTION 2: DATABASE CREATION
-- ============================================================================

-- Development environment
CREATE DATABASE IF NOT EXISTS SANCTIONS_DEV
    DATA_RETENTION_TIME_IN_DAYS = 1
    COMMENT = 'Development environment for Sanctions Risk Analytics Platform';

-- Test / QA environment
CREATE DATABASE IF NOT EXISTS SANCTIONS_TEST
    DATA_RETENTION_TIME_IN_DAYS = 7
    COMMENT = 'Test/QA environment for Sanctions Risk Analytics Platform';

-- Production environment
CREATE DATABASE IF NOT EXISTS SANCTIONS_PROD
    DATA_RETENTION_TIME_IN_DAYS = 90
    COMMENT = 'Production environment for Sanctions Risk Analytics Platform';

-- ============================================================================
-- SECTION 3: SCHEMA CREATION (via stored procedure for consistency)
-- ============================================================================

CREATE OR REPLACE PROCEDURE SANCTIONS_DEV.PUBLIC.CREATE_SCHEMA_STRUCTURE(db_name VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN
    -- Bronze / Raw layer
    EXECUTE IMMEDIATE 'CREATE SCHEMA IF NOT EXISTS ' || db_name || '.RAW
        DATA_RETENTION_TIME_IN_DAYS = 1
        COMMENT = ''Raw data landing zone - Bronze layer''';

    -- Staging layer
    EXECUTE IMMEDIATE 'CREATE SCHEMA IF NOT EXISTS ' || db_name || '.STAGING
        DATA_RETENTION_TIME_IN_DAYS = 1
        COMMENT = ''Staging area for data transformations''';

    -- Silver / Curated layer
    EXECUTE IMMEDIATE 'CREATE SCHEMA IF NOT EXISTS ' || db_name || '.CURATED
        DATA_RETENTION_TIME_IN_DAYS = 7
        COMMENT = ''Curated data - Silver layer''';

    -- Gold / Analytics layer
    EXECUTE IMMEDIATE 'CREATE SCHEMA IF NOT EXISTS ' || db_name || '.ANALYTICS
        DATA_RETENTION_TIME_IN_DAYS = 90
        COMMENT = ''Analytics-ready data - Gold layer''';

    -- Derived / Aggregates
    EXECUTE IMMEDIATE 'CREATE SCHEMA IF NOT EXISTS ' || db_name || '.DERIVED
        DATA_RETENTION_TIME_IN_DAYS = 90
        COMMENT = ''Pre-aggregated derived tables''';

    -- ML / Feature store
    EXECUTE IMMEDIATE 'CREATE SCHEMA IF NOT EXISTS ' || db_name || '.ML
        DATA_RETENTION_TIME_IN_DAYS = 30
        COMMENT = ''Machine learning feature store and model artifacts''';

    -- GenAI layer
    EXECUTE IMMEDIATE 'CREATE SCHEMA IF NOT EXISTS ' || db_name || '.GENAI
        DATA_RETENTION_TIME_IN_DAYS = 30
        COMMENT = ''Generative AI prompts, embeddings, and outputs''';

    -- Governance layer
    EXECUTE IMMEDIATE 'CREATE SCHEMA IF NOT EXISTS ' || db_name || '.GOVERNANCE
        DATA_RETENTION_TIME_IN_DAYS = 365
        COMMENT = ''Data governance, lineage, and audit logs''';

    -- Consumption layer
    EXECUTE IMMEDIATE 'CREATE SCHEMA IF NOT EXISTS ' || db_name || '.CONSUMPTION
        DATA_RETENTION_TIME_IN_DAYS = 30
        COMMENT = ''Consumption layer for Streamlit and external tools''';

    RETURN 'Schema structure created successfully for ' || db_name;
END;
$$;

-- Apply schema structure to all environments
CALL SANCTIONS_DEV.PUBLIC.CREATE_SCHEMA_STRUCTURE('SANCTIONS_DEV');
CALL SANCTIONS_DEV.PUBLIC.CREATE_SCHEMA_STRUCTURE('SANCTIONS_TEST');
CALL SANCTIONS_DEV.PUBLIC.CREATE_SCHEMA_STRUCTURE('SANCTIONS_PROD');

-- ============================================================================
-- SECTION 4: WAREHOUSE CREATION
-- ============================================================================

-- Loading warehouses (data ingestion)
CREATE WAREHOUSE IF NOT EXISTS SANCTIONS_LOADING_WH_XS
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    SCALING_POLICY = 'STANDARD'
    COMMENT = 'XS warehouse for light data loading operations';

CREATE WAREHOUSE IF NOT EXISTS SANCTIONS_LOADING_WH_M
    WAREHOUSE_SIZE = 'MEDIUM'
    AUTO_SUSPEND = 120
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 3
    SCALING_POLICY = 'STANDARD'
    COMMENT = 'Medium warehouse for heavy bulk data loading';

-- Transformation warehouses (dbt runs)
CREATE WAREHOUSE IF NOT EXISTS SANCTIONS_TRANSFORM_WH_XS
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'XS warehouse for dbt dev transformations';

CREATE WAREHOUSE IF NOT EXISTS SANCTIONS_TRANSFORM_WH_M
    WAREHOUSE_SIZE = 'MEDIUM'
    AUTO_SUSPEND = 120
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 4
    SCALING_POLICY = 'STANDARD'
    COMMENT = 'Medium warehouse for dbt production transformations';

-- Analytics warehouses (queries, dashboards)
CREATE WAREHOUSE IF NOT EXISTS SANCTIONS_ANALYTICS_WH_XS
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'XS warehouse for ad-hoc analytics queries';

CREATE WAREHOUSE IF NOT EXISTS SANCTIONS_ANALYTICS_WH_S
    WAREHOUSE_SIZE = 'SMALL'
    AUTO_SUSPEND = 120
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 2
    SCALING_POLICY = 'STANDARD'
    COMMENT = 'Small warehouse for dashboard and reporting queries';

-- ML warehouse
CREATE WAREHOUSE IF NOT EXISTS SANCTIONS_ML_WH_M
    WAREHOUSE_SIZE = 'MEDIUM'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 2
    SCALING_POLICY = 'ECONOMY'
    COMMENT = 'Medium warehouse for ML training and inference workloads';

-- ============================================================================
-- SECTION 5: RESOURCE MONITORS
-- ============================================================================

CREATE OR REPLACE RESOURCE MONITOR ACCOUNT_MONTHLY_MONITOR
    WITH CREDIT_QUOTA = 5000
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
        ON 75 PERCENT DO NOTIFY
        ON 90 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND
        ON 110 PERCENT DO SUSPEND_IMMEDIATE;

ALTER ACCOUNT SET RESOURCE_MONITOR = ACCOUNT_MONTHLY_MONITOR;

CREATE OR REPLACE RESOURCE MONITOR DEV_DAILY_MONITOR
    WITH CREDIT_QUOTA = 50
    FREQUENCY = DAILY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
        ON 80 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND;

ALTER WAREHOUSE SANCTIONS_TRANSFORM_WH_XS SET RESOURCE_MONITOR = DEV_DAILY_MONITOR;
ALTER WAREHOUSE SANCTIONS_ANALYTICS_WH_XS SET RESOURCE_MONITOR = DEV_DAILY_MONITOR;

CREATE OR REPLACE RESOURCE MONITOR PROD_DAILY_MONITOR
    WITH CREDIT_QUOTA = 500
    FREQUENCY = DAILY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
        ON 75 PERCENT DO NOTIFY
        ON 90 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND;

ALTER WAREHOUSE SANCTIONS_LOADING_WH_M SET RESOURCE_MONITOR = PROD_DAILY_MONITOR;
ALTER WAREHOUSE SANCTIONS_TRANSFORM_WH_M SET RESOURCE_MONITOR = PROD_DAILY_MONITOR;

-- ============================================================================
-- SECTION 6: ROLE HIERARCHY
-- ============================================================================

-- Platform admin (top of hierarchy, below SYSADMIN)
CREATE ROLE IF NOT EXISTS SANCTIONS_PLATFORM_ADMIN
    COMMENT = 'Platform administrator - full access to all sanctions objects';

-- Functional roles
CREATE ROLE IF NOT EXISTS SANCTIONS_DATA_ENGINEER
    COMMENT = 'Data engineering - pipeline development and operations';

CREATE ROLE IF NOT EXISTS SANCTIONS_ANALYST
    COMMENT = 'Business analyst - read access to analytics layer';

CREATE ROLE IF NOT EXISTS SANCTIONS_DATA_SCIENTIST
    COMMENT = 'Data scientist - ML model development and feature engineering';

CREATE ROLE IF NOT EXISTS SANCTIONS_COMPLIANCE_OFFICER
    COMMENT = 'Compliance officer - read access to all data for regulatory purposes';

-- Service account roles
CREATE ROLE IF NOT EXISTS SANCTIONS_DBT_RUNNER
    COMMENT = 'Service role for dbt transformations';

CREATE ROLE IF NOT EXISTS SANCTIONS_STREAMLIT_APP
    COMMENT = 'Service role for Streamlit application';

CREATE ROLE IF NOT EXISTS SANCTIONS_ML_PIPELINE
    COMMENT = 'Service role for ML pipeline operations';

-- Role hierarchy
GRANT ROLE SANCTIONS_DATA_ENGINEER     TO ROLE SANCTIONS_PLATFORM_ADMIN;
GRANT ROLE SANCTIONS_ANALYST           TO ROLE SANCTIONS_PLATFORM_ADMIN;
GRANT ROLE SANCTIONS_DATA_SCIENTIST    TO ROLE SANCTIONS_PLATFORM_ADMIN;
GRANT ROLE SANCTIONS_COMPLIANCE_OFFICER TO ROLE SANCTIONS_PLATFORM_ADMIN;
GRANT ROLE SANCTIONS_DBT_RUNNER        TO ROLE SANCTIONS_PLATFORM_ADMIN;
GRANT ROLE SANCTIONS_STREAMLIT_APP     TO ROLE SANCTIONS_PLATFORM_ADMIN;
GRANT ROLE SANCTIONS_ML_PIPELINE       TO ROLE SANCTIONS_PLATFORM_ADMIN;
GRANT ROLE SANCTIONS_PLATFORM_ADMIN    TO ROLE SYSADMIN;

-- ============================================================================
-- SECTION 7: GRANTS - DATABASE & SCHEMA LEVEL
-- ============================================================================

-- Helper procedure to apply grants across all environments
CREATE OR REPLACE PROCEDURE SANCTIONS_DEV.PUBLIC.APPLY_GRANTS(db_name VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN
    -- SANCTIONS_PLATFORM_ADMIN: Full control
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON DATABASE ' || db_name || ' TO ROLE SANCTIONS_PLATFORM_ADMIN';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE ' || db_name || ' TO ROLE SANCTIONS_PLATFORM_ADMIN';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE ' || db_name || ' TO ROLE SANCTIONS_PLATFORM_ADMIN';

    -- SANCTIONS_DATA_ENGINEER: Read/write on RAW, STAGING; read on others
    EXECUTE IMMEDIATE 'GRANT USAGE ON DATABASE ' || db_name || ' TO ROLE SANCTIONS_DATA_ENGINEER';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON SCHEMA ' || db_name || '.RAW TO ROLE SANCTIONS_DATA_ENGINEER';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON SCHEMA ' || db_name || '.STAGING TO ROLE SANCTIONS_DATA_ENGINEER';
    EXECUTE IMMEDIATE 'GRANT USAGE ON SCHEMA ' || db_name || '.CURATED TO ROLE SANCTIONS_DATA_ENGINEER';
    EXECUTE IMMEDIATE 'GRANT USAGE ON SCHEMA ' || db_name || '.ANALYTICS TO ROLE SANCTIONS_DATA_ENGINEER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON ALL TABLES IN SCHEMA ' || db_name || '.CURATED TO ROLE SANCTIONS_DATA_ENGINEER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON ALL TABLES IN SCHEMA ' || db_name || '.ANALYTICS TO ROLE SANCTIONS_DATA_ENGINEER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON FUTURE TABLES IN SCHEMA ' || db_name || '.CURATED TO ROLE SANCTIONS_DATA_ENGINEER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON FUTURE TABLES IN SCHEMA ' || db_name || '.ANALYTICS TO ROLE SANCTIONS_DATA_ENGINEER';

    -- SANCTIONS_ANALYST: Read on ANALYTICS and DERIVED
    EXECUTE IMMEDIATE 'GRANT USAGE ON DATABASE ' || db_name || ' TO ROLE SANCTIONS_ANALYST';
    EXECUTE IMMEDIATE 'GRANT USAGE ON SCHEMA ' || db_name || '.ANALYTICS TO ROLE SANCTIONS_ANALYST';
    EXECUTE IMMEDIATE 'GRANT USAGE ON SCHEMA ' || db_name || '.DERIVED TO ROLE SANCTIONS_ANALYST';
    EXECUTE IMMEDIATE 'GRANT USAGE ON SCHEMA ' || db_name || '.CONSUMPTION TO ROLE SANCTIONS_ANALYST';
    EXECUTE IMMEDIATE 'GRANT SELECT ON ALL TABLES IN SCHEMA ' || db_name || '.ANALYTICS TO ROLE SANCTIONS_ANALYST';
    EXECUTE IMMEDIATE 'GRANT SELECT ON ALL VIEWS IN SCHEMA ' || db_name || '.ANALYTICS TO ROLE SANCTIONS_ANALYST';
    EXECUTE IMMEDIATE 'GRANT SELECT ON FUTURE TABLES IN SCHEMA ' || db_name || '.ANALYTICS TO ROLE SANCTIONS_ANALYST';
    EXECUTE IMMEDIATE 'GRANT SELECT ON FUTURE VIEWS IN SCHEMA ' || db_name || '.ANALYTICS TO ROLE SANCTIONS_ANALYST';
    EXECUTE IMMEDIATE 'GRANT SELECT ON ALL TABLES IN SCHEMA ' || db_name || '.DERIVED TO ROLE SANCTIONS_ANALYST';
    EXECUTE IMMEDIATE 'GRANT SELECT ON FUTURE TABLES IN SCHEMA ' || db_name || '.DERIVED TO ROLE SANCTIONS_ANALYST';

    -- SANCTIONS_DATA_SCIENTIST: Read analytics + ML schema read/write
    EXECUTE IMMEDIATE 'GRANT USAGE ON DATABASE ' || db_name || ' TO ROLE SANCTIONS_DATA_SCIENTIST';
    EXECUTE IMMEDIATE 'GRANT USAGE ON SCHEMA ' || db_name || '.ANALYTICS TO ROLE SANCTIONS_DATA_SCIENTIST';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON SCHEMA ' || db_name || '.ML TO ROLE SANCTIONS_DATA_SCIENTIST';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON SCHEMA ' || db_name || '.GENAI TO ROLE SANCTIONS_DATA_SCIENTIST';
    EXECUTE IMMEDIATE 'GRANT SELECT ON ALL TABLES IN SCHEMA ' || db_name || '.ANALYTICS TO ROLE SANCTIONS_DATA_SCIENTIST';
    EXECUTE IMMEDIATE 'GRANT SELECT ON FUTURE TABLES IN SCHEMA ' || db_name || '.ANALYTICS TO ROLE SANCTIONS_DATA_SCIENTIST';

    -- SANCTIONS_COMPLIANCE_OFFICER: Read access to everything
    EXECUTE IMMEDIATE 'GRANT USAGE ON DATABASE ' || db_name || ' TO ROLE SANCTIONS_COMPLIANCE_OFFICER';
    EXECUTE IMMEDIATE 'GRANT USAGE ON ALL SCHEMAS IN DATABASE ' || db_name || ' TO ROLE SANCTIONS_COMPLIANCE_OFFICER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON ALL TABLES IN DATABASE ' || db_name || ' TO ROLE SANCTIONS_COMPLIANCE_OFFICER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON ALL VIEWS IN DATABASE ' || db_name || ' TO ROLE SANCTIONS_COMPLIANCE_OFFICER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON FUTURE TABLES IN DATABASE ' || db_name || ' TO ROLE SANCTIONS_COMPLIANCE_OFFICER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON FUTURE VIEWS IN DATABASE ' || db_name || ' TO ROLE SANCTIONS_COMPLIANCE_OFFICER';

    -- SANCTIONS_DBT_RUNNER: Transform role - read raw, write curated/analytics/derived
    EXECUTE IMMEDIATE 'GRANT USAGE ON DATABASE ' || db_name || ' TO ROLE SANCTIONS_DBT_RUNNER';
    EXECUTE IMMEDIATE 'GRANT USAGE ON SCHEMA ' || db_name || '.RAW TO ROLE SANCTIONS_DBT_RUNNER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON ALL TABLES IN SCHEMA ' || db_name || '.RAW TO ROLE SANCTIONS_DBT_RUNNER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON FUTURE TABLES IN SCHEMA ' || db_name || '.RAW TO ROLE SANCTIONS_DBT_RUNNER';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON SCHEMA ' || db_name || '.STAGING TO ROLE SANCTIONS_DBT_RUNNER';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON SCHEMA ' || db_name || '.CURATED TO ROLE SANCTIONS_DBT_RUNNER';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON SCHEMA ' || db_name || '.ANALYTICS TO ROLE SANCTIONS_DBT_RUNNER';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON SCHEMA ' || db_name || '.DERIVED TO ROLE SANCTIONS_DBT_RUNNER';

    -- SANCTIONS_STREAMLIT_APP: Read analytics + consumption
    EXECUTE IMMEDIATE 'GRANT USAGE ON DATABASE ' || db_name || ' TO ROLE SANCTIONS_STREAMLIT_APP';
    EXECUTE IMMEDIATE 'GRANT USAGE ON SCHEMA ' || db_name || '.ANALYTICS TO ROLE SANCTIONS_STREAMLIT_APP';
    EXECUTE IMMEDIATE 'GRANT USAGE ON SCHEMA ' || db_name || '.CONSUMPTION TO ROLE SANCTIONS_STREAMLIT_APP';
    EXECUTE IMMEDIATE 'GRANT SELECT ON ALL TABLES IN SCHEMA ' || db_name || '.ANALYTICS TO ROLE SANCTIONS_STREAMLIT_APP';
    EXECUTE IMMEDIATE 'GRANT SELECT ON ALL VIEWS IN SCHEMA ' || db_name || '.ANALYTICS TO ROLE SANCTIONS_STREAMLIT_APP';
    EXECUTE IMMEDIATE 'GRANT SELECT ON FUTURE TABLES IN SCHEMA ' || db_name || '.ANALYTICS TO ROLE SANCTIONS_STREAMLIT_APP';

    -- SANCTIONS_ML_PIPELINE: Read analytics, read/write ML + GENAI
    EXECUTE IMMEDIATE 'GRANT USAGE ON DATABASE ' || db_name || ' TO ROLE SANCTIONS_ML_PIPELINE';
    EXECUTE IMMEDIATE 'GRANT USAGE ON SCHEMA ' || db_name || '.ANALYTICS TO ROLE SANCTIONS_ML_PIPELINE';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON SCHEMA ' || db_name || '.ML TO ROLE SANCTIONS_ML_PIPELINE';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON SCHEMA ' || db_name || '.GENAI TO ROLE SANCTIONS_ML_PIPELINE';
    EXECUTE IMMEDIATE 'GRANT SELECT ON ALL TABLES IN SCHEMA ' || db_name || '.ANALYTICS TO ROLE SANCTIONS_ML_PIPELINE';
    EXECUTE IMMEDIATE 'GRANT SELECT ON FUTURE TABLES IN SCHEMA ' || db_name || '.ANALYTICS TO ROLE SANCTIONS_ML_PIPELINE';

    RETURN 'Grants applied successfully for ' || db_name;
END;
$$;

-- Apply grants to all environments
CALL SANCTIONS_DEV.PUBLIC.APPLY_GRANTS('SANCTIONS_DEV');
CALL SANCTIONS_DEV.PUBLIC.APPLY_GRANTS('SANCTIONS_TEST');
CALL SANCTIONS_DEV.PUBLIC.APPLY_GRANTS('SANCTIONS_PROD');

-- Warehouse grants
GRANT USAGE ON WAREHOUSE SANCTIONS_LOADING_WH_XS    TO ROLE SANCTIONS_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE SANCTIONS_LOADING_WH_M     TO ROLE SANCTIONS_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE SANCTIONS_TRANSFORM_WH_XS  TO ROLE SANCTIONS_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE SANCTIONS_TRANSFORM_WH_XS  TO ROLE SANCTIONS_DBT_RUNNER;
GRANT USAGE ON WAREHOUSE SANCTIONS_TRANSFORM_WH_M   TO ROLE SANCTIONS_DBT_RUNNER;
GRANT USAGE ON WAREHOUSE SANCTIONS_ANALYTICS_WH_XS  TO ROLE SANCTIONS_ANALYST;
GRANT USAGE ON WAREHOUSE SANCTIONS_ANALYTICS_WH_S   TO ROLE SANCTIONS_ANALYST;
GRANT USAGE ON WAREHOUSE SANCTIONS_ANALYTICS_WH_XS  TO ROLE SANCTIONS_DATA_SCIENTIST;
GRANT USAGE ON WAREHOUSE SANCTIONS_ANALYTICS_WH_XS  TO ROLE SANCTIONS_COMPLIANCE_OFFICER;
GRANT USAGE ON WAREHOUSE SANCTIONS_ANALYTICS_WH_S   TO ROLE SANCTIONS_COMPLIANCE_OFFICER;
GRANT USAGE ON WAREHOUSE SANCTIONS_ANALYTICS_WH_XS  TO ROLE SANCTIONS_STREAMLIT_APP;
GRANT USAGE ON WAREHOUSE SANCTIONS_ML_WH_M          TO ROLE SANCTIONS_DATA_SCIENTIST;
GRANT USAGE ON WAREHOUSE SANCTIONS_ML_WH_M          TO ROLE SANCTIONS_ML_PIPELINE;

-- ============================================================================
-- SECTION 8: NETWORK POLICY
-- ============================================================================

CREATE OR REPLACE NETWORK POLICY SANCTIONS_NETWORK_POLICY
    ALLOWED_IP_LIST = (
        '0.0.0.0/0'            -- PLACEHOLDER: Replace with actual office/VPN CIDRs
    )
    BLOCKED_IP_LIST = ()
    COMMENT = 'Network policy for Sanctions Platform - restrict to known IPs in production';

-- NOTE: Apply to account only after configuring actual IP ranges
-- ALTER ACCOUNT SET NETWORK_POLICY = SANCTIONS_NETWORK_POLICY;

-- ============================================================================
-- SECTION 9: OBJECT TAGGING FOR GOVERNANCE
-- ============================================================================

USE DATABASE SANCTIONS_PROD;
USE SCHEMA GOVERNANCE;

CREATE OR REPLACE TAG COST_CENTER
    ALLOWED_VALUES 'ENGINEERING', 'ANALYTICS', 'COMPLIANCE', 'DATA_SCIENCE', 'PLATFORM'
    COMMENT = 'Cost attribution tag for warehouse and compute usage';

CREATE OR REPLACE TAG DATA_CLASSIFICATION
    ALLOWED_VALUES 'PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED'
    COMMENT = 'Data classification level for governance';

CREATE OR REPLACE TAG PII_FLAG
    ALLOWED_VALUES 'TRUE', 'FALSE'
    COMMENT = 'Identifies objects containing Personally Identifiable Information';

CREATE OR REPLACE TAG DATA_DOMAIN
    ALLOWED_VALUES 'TRADE', 'COUNTERPARTY', 'VESSEL', 'SANCTIONS', 'SCREENING', 'REFERENCE'
    COMMENT = 'Business domain classification';

CREATE OR REPLACE TAG DATA_LAYER
    ALLOWED_VALUES 'RAW', 'STAGING', 'CURATED', 'ANALYTICS', 'DERIVED', 'ML', 'GENAI'
    COMMENT = 'Data layer in the medallion architecture';

-- Apply tags to warehouses
ALTER WAREHOUSE SANCTIONS_LOADING_WH_XS   SET TAG COST_CENTER = 'ENGINEERING';
ALTER WAREHOUSE SANCTIONS_LOADING_WH_M    SET TAG COST_CENTER = 'ENGINEERING';
ALTER WAREHOUSE SANCTIONS_TRANSFORM_WH_XS SET TAG COST_CENTER = 'ENGINEERING';
ALTER WAREHOUSE SANCTIONS_TRANSFORM_WH_M  SET TAG COST_CENTER = 'ENGINEERING';
ALTER WAREHOUSE SANCTIONS_ANALYTICS_WH_XS SET TAG COST_CENTER = 'ANALYTICS';
ALTER WAREHOUSE SANCTIONS_ANALYTICS_WH_S  SET TAG COST_CENTER = 'ANALYTICS';
ALTER WAREHOUSE SANCTIONS_ML_WH_M         SET TAG COST_CENTER = 'DATA_SCIENCE';

-- ============================================================================
-- SECTION 10: SERVICE ACCOUNTS
-- ============================================================================

-- DBT Runner service account
CREATE USER IF NOT EXISTS SVC_DBT_RUNNER
    LOGIN_NAME = 'SVC_DBT_RUNNER'
    DISPLAY_NAME = 'DBT Runner Service Account'
    MUST_CHANGE_PASSWORD = FALSE
    DEFAULT_ROLE = 'SANCTIONS_DBT_RUNNER'
    DEFAULT_WAREHOUSE = 'SANCTIONS_TRANSFORM_WH_M'
    DEFAULT_NAMESPACE = 'SANCTIONS_PROD.RAW'
    COMMENT = 'Service account for dbt transformation pipelines';

GRANT ROLE SANCTIONS_DBT_RUNNER TO USER SVC_DBT_RUNNER;

-- Streamlit App service account
CREATE USER IF NOT EXISTS SVC_STREAMLIT_APP
    LOGIN_NAME = 'SVC_STREAMLIT_APP'
    DISPLAY_NAME = 'Streamlit Application Service Account'
    MUST_CHANGE_PASSWORD = FALSE
    DEFAULT_ROLE = 'SANCTIONS_STREAMLIT_APP'
    DEFAULT_WAREHOUSE = 'SANCTIONS_ANALYTICS_WH_XS'
    DEFAULT_NAMESPACE = 'SANCTIONS_PROD.CONSUMPTION'
    COMMENT = 'Service account for Streamlit dashboard application';

GRANT ROLE SANCTIONS_STREAMLIT_APP TO USER SVC_STREAMLIT_APP;

-- ML Pipeline service account
CREATE USER IF NOT EXISTS SVC_ML_PIPELINE
    LOGIN_NAME = 'SVC_ML_PIPELINE'
    DISPLAY_NAME = 'ML Pipeline Service Account'
    MUST_CHANGE_PASSWORD = FALSE
    DEFAULT_ROLE = 'SANCTIONS_ML_PIPELINE'
    DEFAULT_WAREHOUSE = 'SANCTIONS_ML_WH_M'
    DEFAULT_NAMESPACE = 'SANCTIONS_PROD.ML'
    COMMENT = 'Service account for ML training and inference pipelines';

GRANT ROLE SANCTIONS_ML_PIPELINE TO USER SVC_ML_PIPELINE;

-- ============================================================================
-- KEY PAIR AUTHENTICATION SETUP (execute per service account)
-- ============================================================================
-- Generate RSA key pair locally:
--   openssl genrsa 2048 | openssl pkcs8 -topk8 -inform PEM -out rsa_key.p8 -nocrypt
--   openssl rsa -in rsa_key.p8 -pubout -out rsa_key.pub
--
-- Then set the public key:
--   ALTER USER SVC_DBT_RUNNER SET RSA_PUBLIC_KEY='<paste_public_key_here>';
--   ALTER USER SVC_STREAMLIT_APP SET RSA_PUBLIC_KEY='<paste_public_key_here>';
--   ALTER USER SVC_ML_PIPELINE SET RSA_PUBLIC_KEY='<paste_public_key_here>';
-- ============================================================================

-- End of 001_account_setup.sql
